const employeeColumns = [
  {
    dataField: "EmployeeID",
    caption: "Mã nhân viên",
    dataType: "number",
    alignment: "left",
    customizeText: (e) => "NV" + e.value,
    fixed: true,
    width: 150,
    visible: true,
  },
  {
    dataField: "FullName",
    caption: "Tên nhân viên",
    dataType: "string",
    alignment: "left",
    fixed: true,
    width: 150,
    visible: true,
  },
  {
    dataField: "Position",
    caption: "Chức danh",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },
  {
    dataField: "BirthDate",
    caption: "Ngày sinh",
    dataType: "date",
    alignment: "center",
    width: 180,
    visible: true,
  },
  {
    dataField: "Address",
    caption: "Địa chỉ",
    dataType: "string",
    alignment: "left",
    width: 240,
    visible: true,
  },
  {
    dataField: "City",
    caption: "Thành phố",
    dataType: "string",
    alignment: "left",
    width: 150,
    visible: true,
  },
  {
    dataField: "Region",
    caption: "Khu vực",
    dataType: "string",
    alignment: "left",
    width: 150,
    visible: true,
  },
  {
    dataField: "PostalCode",
    caption: "Mã bưu chính",
    dataType: "string",
    alignment: "left",
    width: 150,
    visible: true,
  },
  {
    dataField: "Country",
    caption: "Quốc gia",
    dataType: "string",
    alignment: "left",
    width: 150,
    visible: true,
  },
];

export default employeeColumns;
