import enums from "@/enum/enum";
import { formatDate } from "devextreme/localization";
import { getRelationship } from "@/api/mock-data";

export const employeeColumns = [
  {
    dataField: "EmployeeCode",
    caption: "Mã nhân viên",
    dataType: "number",
    alignment: "left",
    fixed: true,
    width: 150,
    visible: true,
  },
  {
    dataField: "FullName",
    caption: "Họ và tên",
    dataType: "string",
    alignment: "left",
    fixed: true,
    width: 150,
    visible: true,
  },
  {
    dataField: "DateOfBirth",
    caption: "Ngày sinh",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    width: 180,
    visible: true,
  },
  {
    dataField: "GenderName",
    caption: "Giới tính",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },
  {
    dataField: "TaxCode",
    caption: "Mã số thuế",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },
  {
    dataField: "EmployeeType",
    caption: "Loại đối tượng",
    dataType: "string",
    customizeText: (e) => (e.value == enums.employeeType.employee ? "Nhân viên" : "Vãng lai"),
    alignment: "left",
    width: 180,
    visible: true,
  },
  {
    dataField: "JobPositionName",
    caption: "Vị trí/Chức vụ",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },

  {
    dataField: "OrganizationUnitName",
    caption: "Bộ phận/Phòng ban",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },

  {
    dataField: "ContractMintaxTypeName",
    caption: "Loại hợp đồng",
    dataType: "string",
    alignment: "left",
    width: 180,
    visible: true,
  },

  {
    dataField: "ProbationDate",
    caption: "Ngày học việc",
    dataType: "string",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    width: 180,
    visible: true,
  },
  {
    dataField: "HireDate",
    caption: "Ngày thử việc",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    width: 180,
    visible: true,
  },

  {
    dataField: "ReceiveDate",
    caption: "Ngày chính thức",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    width: 180,
    visible: true,
  },
  {
    dataField: "TerminationDate",
    caption: "Ngày nghỉ việc",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    width: 180,
    visible: true,
  },
  {
    dataField: "Email",
    caption: "Email",
    dataType: "string",
    alignment: "left",
    width: 280,
    visible: true,
  },
  {
    dataField: "IdentifyNumber",
    caption: "Số CMND/CCCD/Hộ chiếu",
    trueText: "Số Chứng minh nhân dân/Căn cước công dân/Hộ chiếu",
    dataType: "string",
    alignment: "left",
    width: 220,
    visible: true,
  },
  {
    dataField: "EmployeeStatus",
    caption: "Trạng thái làm việc",
    dataType: "string",
    customizeText: (e) =>
      e.value == enums.workStatus.currentlyEmployed ? "Đang làm việc" : "Đã nghỉ việc",
    alignment: "center",
    width: 180,
    visible: true,
  },
];

export const excelExportSheets = [
  {
    SheetName: "Thông tin người nộp thuế",
    SheetTitle: "Danh sách xuất khẩu thông tin của người nộp thuế",
    SheetKey: "Employee",
    ColumnGroups: [
      {
        Title: "Thông tin công việc của đối tượng nhân viên",
        StartColumn: 17,
        EndColumn: 21,
        Background: "#FFDEFA",
      },
      {
        Title: "Hộ khẩu thường trú",
        StartColumn: 22,
        EndColumn: 26,
        Background: "#FCFFA6",
      },
      {
        Title: "Chỗ ở hiện nay",
        StartColumn: 27,
        EndColumn: 31,
        Background: "#C1FFD7",
      },
    ],
    Columns: [
      {
        DataField: "EmployeeTypeName",
        Caption: "Loại đối tượng",
        Index: 1,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "EmployeeCode",
        Caption: "Mã người nộp thuế (*)",
        Index: 2,
        Width: 180,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "FullName",
        Caption: "Họ tên (*)",
        Index: 3,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "OrganizationUnitId",
        Caption: "Mã bộ phận/phòng ban",
        Index: 4,
        Width: 180,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "TaxCode",
        Caption: "Mã số thuế",
        Index: 5,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyTypeName",
        Caption: "Loại giấy tờ",
        Index: 6,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyNumber",
        Caption: "Số CMND/CCCD/Hộ chiếu",
        Index: 7,
        Width: 210,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyDate",
        Caption: "Ngày cấp",
        Index: 8,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyIssuedPlaceName",
        Caption: "Nơi cấp",
        Index: 9,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "DateOfBirth",
        Caption: "Ngày sinh",
        Index: 10,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "GenderName",
        Caption: "Giới tính",
        Index: 11,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "NationalName",
        Caption: "Quốc tịch",
        Index: 12,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "ContractMintaxTypeName",
        Caption: "Loại hợp đồng",
        Index: 13,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "Mobile",
        Caption: "Điện thoại",
        Index: 14,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "Email",
        Caption: "Email",
        Index: 15,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "EmployeeStatusName",
        Caption: "Trạng thái",
        Index: 16,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },

      // Thông tin công việc của nhân viên
      {
        DataField: "JobPositionId",
        Caption: "Mã vị trí công việc (*)",
        Index: 17,
        Width: 180,
        Alignment: "left",
        HeaderBackground: "#FFDEFA",
      },
      {
        DataField: "ProbationDate",
        Caption: "Ngày học việc",
        Index: 18,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#FFDEFA",
      },
      {
        DataField: "HireDate",
        Caption: "Ngày thử việc",
        Index: 19,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#FFDEFA",
      },
      {
        DataField: "ReceiveDate",
        Caption: "Ngày chính thức",
        Index: 20,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#FFDEFA",
      },
      {
        DataField: "TerminationDate",
        Caption: "Ngày nghỉ việc",
        Index: 21,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#FFDEFA",
      },

      // Hộ khẩu thường trú
      {
        DataField: "NativeCountryName",
        Caption: "Quốc gia \n (HKTT)",
        Index: 22,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "NativeProvinceName",
        Caption: "Tỉnh/TP \n (HKTT)",
        Index: 23,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "NativeDistrictName",
        Caption: "Quận/Huyện \n (HKTT)",
        Index: 24,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "NativeWardName",
        Caption: "Phường/Xã \n (HKTT)",
        Index: 25,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "NativeStreetHouseNumber",
        Caption: "Số nhà/Đường phố \n (HKTT)",
        Index: 26,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },

      // Chỗ ở hiện nay
      {
        DataField: "CurrentCountryName",
        Caption: "Quốc gia \n (COHN)",
        Index: 27,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "CurrentProvinceName",
        Caption: "Tỉnh/TP \n (COHN)",
        Index: 28,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "CurrentDistrictName",
        Caption: "Quận/Huyện \n (COHN)",
        Index: 29,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "CurrentWardName",
        Caption: "Phường/Xã \n (COHN)",
        Index: 30,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "CurrentStreetHouseNumber",
        Caption: "Số nhà/Đường phố \n (COHN)",
        Index: 31,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
    ],
  },

  // --------------- SHEET THÀNH VIÊN GIA ĐÌNH ---------------
  {
    SheetName: "Thông tin gia đình",
    SheetTitle: "Danh sách xuất khẩu thông tin của người nộp thuế",
    SheetKey: "EmployeeRelationship",
    ColumnGroups: [
      {
        Title: "Hộ khẩu thường trú",
        StartColumn: 12,
        EndColumn: 15,
        Background: "#FCFFA6",
      },
      {
        Title: "Chỗ ở hiện nay",
        StartColumn: 16,
        EndColumn: 19,
        Background: "#C1FFD7",
      },
      {
        Title: "Thông tin khai sinh",
        StartColumn: 20,
        EndColumn: 26,
        Background: "#61BDF6",
      },
      {
        Title: "Thông tin giảm trừ",
        StartColumn: 27,
        EndColumn: 30,
        Background: "#BEF2FF",
      },
    ],
    Columns: [
      {
        DataField: "EmployeeCode",
        Caption: "Mã người nộp thuế trên sheet \n Thông tin người nộp thuế",
        Index: 1,
        Width: 220,
        Alignment: "left",
        FontSize: 11,
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "FullName",
        Caption: "Họ tên thành viên (*)",
        Index: 2,
        Width: 180,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "RelationshipName",
        Caption: "Quan hệ (*)",
        Index: 3,
        Width: 140,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "DateOfBirth",
        Caption: "Ngày sinh",
        Index: 4,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "GenderName",
        Caption: "Giới tính",
        Index: 5,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "TaxCode",
        Caption: "Mã số thuế",
        Index: 6,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "NationalityName",
        Caption: "Quốc tịch",
        Index: 7,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyKindOfPaperName",
        Caption: "Loại giấy tờ",
        Index: 8,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyPaperNumber",
        Caption: "Số CMND/CCCD/Hộ chiếu",
        Index: 9,
        Width: 210,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyNumberIssuedDate",
        Caption: "Ngày cấp",
        Index: 10,
        Width: 150,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "IdentifyNumberIssuedPlaceName",
        Caption: "Nơi cấp",
        Index: 11,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },

      // Hộ khẩu thường trú
      {
        DataField: "FamilyPermanentAddressProvinceName",
        Caption: "Tỉnh/TP \n (HKTT)",
        Index: 12,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "FamilyPermanentAddressDistrictName",
        Caption: "Quận/Huyện \n (HKTT)",
        Index: 13,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "FamilyPermanentAddressWardName",
        Caption: "Phường/Xã \n (HKTT)",
        Index: 14,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },
      {
        DataField: "FamilyPermanentAddressStreetHouseNumber",
        Caption: "Số nhà/Đường phố \n (HKTT)",
        Index: 15,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#FCFFA6",
      },

      // Chỗ ở hiện nay
      {
        DataField: "FamilyCurrentProvinceName",
        Caption: "Tỉnh/TP \n (COHN)",
        Index: 16,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "FamilyCurrentDistrictName",
        Caption: "Quận/Huyện \n (COHN)",
        Index: 17,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "FamilyCurrentWardName",
        Caption: "Phường/Xã \n (COHN)",
        Index: 18,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },
      {
        DataField: "FamilyCurrentStreetHouseNumber",
        Caption: "Số nhà/Đường phố \n (COHN)",
        Index: 19,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#C1FFD7",
      },

      // Thông tin khai sinh
      {
        DataField: "DependentNumber",
        Caption: "Số khai sinh",
        Index: 20,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "NumberBook",
        Caption: "Quyển số",
        Index: 21,
        Width: 140,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "BirthCertificationIssueDate",
        Caption: "Ngày cấp giấy khai sinh",
        Index: 22,
        Width: 180,
        Alignment: "center",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "CountryName",
        Caption: "Quốc gia",
        Index: 23,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "ProvinceName",
        Caption: "Tỉnh/TP",
        Index: 24,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "DistrictName",
        Caption: "Quận/Huyện",
        Index: 25,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },
      {
        DataField: "WardName",
        Caption: "Phường/Xã",
        Index: 26,
        Width: 160,
        Alignment: "left",
        HeaderBackground: "#61BDF6",
      },

      // Thông tin giảm trừ
      {
        DataField: "IsDependent",
        Caption: "Là người phụ thuộc",
        Index: 27,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "DeductionStartDate",
        Caption: "Giảm trừ từ tháng",
        Index: 28,
        Width: 160,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "DeductionEndDate",
        Caption: "Giảm trừ đến tháng",
        Index: 29,
        Width: 160,
        Alignment: "center",
        HeaderBackground: "#BEF2FF",
      },
      {
        DataField: "Description",
        Caption: "Ghi chú",
        Index: 30,
        Width: 150,
        Alignment: "left",
        HeaderBackground: "#BEF2FF",
      },
    ],
  },
];

export const employeeRelationshipColumns = [
  {
    dataField: "FullName",
    caption: "Họ và tên",
    dataType: "string",
    alignment: "left",
    fixed: false,
    width: 150,
    visible: true,
  },
  {
    dataField: "TaxCode",
    caption: "Mã số thuế",
    dataType: "string",
    alignment: "left",
    fixed: false,
    width: 150,
    visible: true,
  },
  {
    dataField: "IsDependent",
    caption: "Là người phụ thuộc",
    dataType: "string",
    alignment: "center",
    fixed: false,
    width: 180,
    visible: true,
  },
  {
    dataField: "DateOfBirth",
    caption: "Ngày sinh",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    fixed: false,
    width: 150,
    visible: true,
  },
  {
    dataField: "Relationship",
    caption: "Quan hệ",
    dataType: "string",
    customizeText: (e) => getRelationship(e.value)?.label,
    alignment: "left",
    fixed: false,
    width: 100,
    visible: true,
  },
  {
    dataField: "DeductionStartDate",
    caption: "Giảm trừ từ",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    fixed: false,
    width: 150,
    visible: true,
  },
  {
    dataField: "DeductionEndDate",
    caption: "Giảm trừ đến",
    dataType: "date",
    customizeText: (e) => (e.value ? formatDate(new Date(e.value), "dd/MM/yyyy") : ""),
    alignment: "center",
    fixed: false,
    width: 150,
    visible: true,
  },
];
